### ISSUE TITLE
Writing Master Issue

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/oauth#15]
- [x] A) Change `example` chapter to be the farm app and the fantasy chicken league
- [x] B)  `farm_robot` - modify this to use the new example
- [x] C) `coop` introduce the idea of an application and use the access token
-  [x] D) `client-credentials.rst` - write this chapter!
